### ISSUE TITLE
fail tests with Role::Tiny-1.3.2

### ISSUE THREAD

**Issue by powerman** [Leont/dist-zilla-plugin-substitute#4]
With Role::Tiny-1.3.2 I got this error:
```
t/basic.t ............... You can only consume roles, Throwable is not a Moose role at /usr/lib64/perl5/vendor_perl/5.20.2/x86_64-linux/Moose/Util.pm line 138.
```
With Role::Tiny-1.3.4 it works ok.

I'm not sure which module should depend on Role::Tiny-1.3.4 - this one or Throwable.

**Comment by Leont** [comment]
I'm not doing anything that comes close to Throwable or Role::Tiny. This sounds like there's a bug somewhere else, but I wouldn't have a clue where exactly.
